<?php /** @var \Magento\Framework\Escaper $escaper */ ?>

<div>
    <p class="oleksiib-regular-customers-cms"><?= $escaper->escapeHtml(__('Please register to participate in the loyalty program')) ?></p>
    <button class="action primary"
            data-mage-init='{"oleksiibRegularCustomersButton":{}}'>
        <span><?= $escaper->escapeHtml(__('Participate in the program')) ?></span>
    </button>
</div>
